version: '3.4'

services:
  redis:
   container_name: redis
   restart: always
   ports:
    - 6379:6379
  rabbitmq:
   container_name: rabbitmq
   restart: always
   ports:
      - "5672:5672"
      - "15672:15672" 
  serviceconfigurationdb:
    container_name: serviceconfigurationdb
    restart: always
    ports:
       - "1433:1433"
    volumes:
      - serviceconfigurationdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12**
  # configurationreaderbackgrounddb:
  #   container_name: configurationreaderbackgrounddb
  #   restart: always
  #   ports:
  #     - "1444:1433"
  #   volumes:
  #     - configurationreaderbackgrounddb_volume:/var/opt/mssql
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=Password12*
  configurationreader.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:SqlServer=Server=serviceconfigurationdb,1433;Database=ConfigurationReader;User=sa; Password=Password12**"

    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - serviceconfigurationdb
  configurationreader.backgroud:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - "ConnectionStrings:SqlServer=Server=serviceconfigurationdb,1433;Database=ConfigurationReader;User=sa; Password=Password12**"
      - RedisSettings:Port=6379
      - RedisSettings:Host=redis
      - RabbitMqSettings:Url=rabbitmq
      - RabbitMqSettings:Username=guest
      - RabbitMqSettings:Password=guest
    depends_on:
      - serviceconfigurationdb
      - rabbitmq
      - redis
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  configurationreader.webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5010:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - configurationreader.api
